package:
  name: hfold
  version: "1.0.9"

source:
  path: ..
  # git_url: https://github.com/HosnaJabbari/HFold.git
  # git_rev: (latest tag)

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - make  # [not win]
    - ninja  # Optional on Windows, can be used instead of NMake
    
  host:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]
  run:
    - libstdcxx-ng    # [linux]
    - libcxx          # [osx]

about:
  home: https://github.com/HosnaJabbari/HFold
  license: "MIT"
  license_file: LICENSE
  summary: "HFold is an algorithm for predicting pseudoknotted secondary structures of RNA using strict Hierarchical Folding."
  description: |
    HFold predicts RNA secondary structure using a hierarchical folding approach.
  dev_url: https://github.com/HosnaJabbari/HFold

extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - HFold --help
