package:
  name: hfold
  version: "1.1.1"

source:
  path: ..
  #git_url: https://github.com/HosnaJabbari/HFoldTest.git
  #git_rev: "{{ raw_tag }}"

build:
  number: 0
  ignore_run_exports:
    - python

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.1
    - make
    - sysroot_linux-aarch64

  host:
    - libgcc-ng >= 14.2.0       # [linux]
    - libstdcxx-ng >= 14.2.0    # [linux]
    - libcxx          # [osx]
  run:
    - libgcc-ng >= 14.2.0      # [linux]
    - libstdcxx-ng >= 14.2.0    # [linux]
    - libcxx          # [osx]

about:
  home: https://github.com/HosnaJabbari/HFoldTest
  license: "MIT"
  license_file: LICENSE
  summary: "HFold is an algorithm for predicting pseudoknotted secondary structures of RNA using strict Hierarchical Folding."
  description: |
    HFold predicts RNA secondary structure using a hierarchical folding approach.
  dev_url: https://github.com/HosnaJabbari/HFoldTest

extra:
  recipe-maintainers:
    - PointlessUser

test:
  commands:
    - HFold --help
