name: Conda Build & Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            subdir: linux-64
          - os: macos-latest
            subdir: osx-arm64
          - os: macos-13
            subdir: osx-64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#https://github.com/conda/actions/blob/main/canary-release/action.yml
      - name: Build & Upload Conda Package
        uses: conda/actions/canary-release@a46e86a61fbca7dec20c0df4c6b95ce3b4ea2263 # v25.2.0
        with:
          package-name: ${{ github.event.repository.name }}
          subdir: ${{ matrix.subdir }}
          anaconda-org-channel: yaalshama
          anaconda-org-label: main
          anaconda-org-token: ${{ secrets.ANACONDA_API_TOKEN }}
          conda-build-path: conda_recipe
      
          # Let Conda build for the correct subdir, do the work in /tmp,
          # and still place the final packages under ./pkgs/<subdir>/...
          conda-build-arguments: "--subdir ${{ matrix.subdir }} --croot /tmp/conda-build --output-folder ./pkgs"
