name: Conda Build & Upload

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: latest
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Install conda-build & anaconda-client
        run: conda install -y conda-build anaconda-client

      - name: Build Conda Package
        run: |
          conda build .
          built_pkg=$(conda build . --output)
          echo "Built package: $built_pkg"

      - name: Convert Conda Package
        run: |
          # Create an output folder
          mkdir -p converted_pkgs

          # Grab the built package path again
          built_pkg=$(conda build . --output)
          
          # Convert to all platforms (linux-64, osx-64, win-64, etc.)
          conda convert "$built_pkg" --platform all --output-dir converted_pkgs

          echo "Converted packages:"
          ls -R converted_pkgs

      - name: Upload Packages to Anaconda
        if: success()
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          # Upload all converted *.tar.bz2 packages
          conda run -n base anaconda -t "$ANACONDA_API_TOKEN" upload \
            --user yaalshama --label main --force converted_pkgs/*/*.tar.bz2
