name: Conda Build & Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        architecture: [x64, ARM64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Install conda-build & anaconda-client
        shell: bash
        run: |
          conda install -y conda-build anaconda-client

      - name: Build Conda Package
        shell: bash
        run: |
          conda build .

      - name: Upload Package to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        shell: bash
        run: |
          built_pkg=$(conda build . --output)
          echo "Built package: $built_pkg"
          conda run -n base anaconda -t $ANACONDA_API_TOKEN upload --user yaalshama --label main --force $built_pkg
