name: Conda Build & Upload

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            subdir: linux-64
          - os: macos-latest
            subdir: osx-arm64
          - os: macos-13
            subdir: osx-64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Upload Conda Package
        uses: conda/actions/canary-release@a46e86a61fbca7dec20c0df4c6b95ce3b4ea2263
        with:
          # The name of your conda package; you can hardcode or 
          # dynamically use the repo name:
          package-name: ${{ github.event.repository.name }}
          
          # Matches the subdir from the matrix above:
          subdir: ${{ matrix.subdir }}
          
          # The Anaconda.org "channel" or "user" you'd like to upload to:
          anaconda-org-channel: yaalshama
          
          # A label/tag for your package in that channel (e.g. "main", "dev", etc.)
          anaconda-org-label: main

          # Where the recipe is located
          conda-build-path: conda_recipe

          conda-build-args: "--croot=/tmp/pkgs"
          
          # Make sure to store this token in your GitHub Secrets!
          anaconda-org-token: ${{ secrets.ANACONDA_API_TOKEN }}
